/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Fri Sep 15 22:44:33 2017. */

#include "SetPointSimple.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t blox_SetPointSimple_fields[2] = {
    PB_FIELD(  1, SINT32  , REQUIRED, STATIC  , FIRST, blox_SetPointSimple, value, value, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
