/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.8 at Mon Sep 18 12:21:14 2017. */

#ifndef PB_BLOX_SPARSEDATA_PB_H_INCLUDED
#define PB_BLOX_SPARSEDATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _blox_SparseDataComplete {
    int16_t value1;
    int16_t value2;
/* @@protoc_insertion_point(struct:blox_SparseDataComplete) */
} blox_SparseDataComplete;

typedef struct _blox_SparseDataPartial {
    int16_t value2;
/* @@protoc_insertion_point(struct:blox_SparseDataPartial) */
} blox_SparseDataPartial;

/* Default values for struct fields */

/* Initializer values for message structs */
#define blox_SparseDataComplete_init_default     {0, 0}
#define blox_SparseDataPartial_init_default      {0}
#define blox_SparseDataComplete_init_zero        {0, 0}
#define blox_SparseDataPartial_init_zero         {0}

/* Field tags (for use in manual encoding/decoding) */
#define blox_SparseDataComplete_value1_tag       1
#define blox_SparseDataComplete_value2_tag       2
#define blox_SparseDataPartial_value2_tag        2

/* Struct field encoding specification for nanopb */
extern const pb_field_t blox_SparseDataComplete_fields[3];
extern const pb_field_t blox_SparseDataPartial_fields[2];

/* Maximum encoded size of messages (where known) */
#define blox_SparseDataComplete_size             12
#define blox_SparseDataPartial_size              6

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define SPARSEDATA_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
