/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Sep 18 12:21:14 2017. */

#include "SparseData.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t blox_SparseDataComplete_fields[3] = {
    PB_FIELD(  1, SINT32  , SINGULAR, STATIC  , FIRST, blox_SparseDataComplete, value1, value1, 0),
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , OTHER, blox_SparseDataComplete, value2, value1, 0),
    PB_LAST_FIELD
};

const pb_field_t blox_SparseDataPartial_fields[2] = {
    PB_FIELD(  2, SINT32  , SINGULAR, STATIC  , FIRST, blox_SparseDataPartial, value2, value2, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
