/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.8 at Mon Sep 18 12:21:14 2017. */

#include "Temperatures.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t blox_temperature_fields[2] = {
    PB_FIELD(  1, SINT32  , SINGULAR, STATIC  , FIRST, blox_temperature, temp_t, temp_t, 0),
    PB_LAST_FIELD
};

const pb_field_t blox_temperature_long_fields[2] = {
    PB_FIELD(  1, SINT32  , SINGULAR, STATIC  , FIRST, blox_temperature_long, temp_long_t, temp_long_t, 0),
    PB_LAST_FIELD
};

const pb_field_t blox_temperature_precise_fields[2] = {
    PB_FIELD(  1, SINT32  , SINGULAR, STATIC  , FIRST, blox_temperature_precise, temp_precise_t, temp_precise_t, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
